### ISSUE TITLE
Import fluor in my JS file

### ISSUE THREAD

**Issue by CyrilKrylatov** [fluorjs/fluor#9]
Hi there,

It should be great to have the possibility to import fluor in our own JS file, like this:

`import * from fluor`

and furthermore, choose what we want to import to optimise the bundle's size, like:

`import { addClass, toggle } from fluor`

and why not, add the possibility to have a list of checkboxes on the website, clic what we want to import and tadam you generate the import syntax for us.

Cheers mate.

Edit: please note that I'm opening this issue because I don't want any JavaScript on my Twig templates for the moment, as it's not minified or anything.

**Comment by madx** [comment]
So I gave this a bit of thought and I'm a bit puzzled because even if that is a nice feature to have, Fluor is _designed_ to work with special `<script type="fluor">` tags and exposing the internal molecule API[1] isn't so easy. Exporting per se is not an issue since we're dealing with a module, but functions like `on`, `addClass` ... are internal to the objects that Fluor creates. That means you'd have to import some low level functions to be able to create molecules by yourself 

Could you give me a bit more details on how you want to use it?

[1]: Molecules are Fluor objects that are tied to a specific DOM node and that run some Fluor code.

**Comment by CyrilKrylatov** [comment]
I don't really know how to use it but I do know that I bother me to do `import jquery` when I just want its `$.ajax` function, I don't need `.addClass`, DOM events or something else for it. I'm not comparing Fluor with jQuery of course since Fluor is way better than that but you got the main idea.

Look, if you're saying that importing modules won't be easy, nevermind then ; I'll import the whole framework, for the moment it's not that big after all.

**Comment by madx** [comment]
In Fluor you need to have special attributes in your templates anyway, and the goal is to have the runtime as small as possible so you can add it to your page (its a bit less that 2kb minified and gzipped as of 0.3.1) and spice your page with some Fluor code to add simple interactions.

You can see and example at https://fluorjs.github.io/#Guide

**Comment by CyrilKrylatov** [comment]
I don't mind at hall for having some special attributes in my template but I do mind if I have some JavaScript code on my templates. I worked so hard to remove some jQuery code that were into them that I can't put new JavaScript code.

But hey if that's not possible to import Fluor in my JS files, don't mind me and I'll use the framework as expected!

**Comment by madx** [comment]
I'm not saying I don't wanna add it, I'm just searching for the right way to do it

I think you would have to import a function from the package and call it on a target DOM node to inject your fluor code in it. 

If you're using React you can do like I do on the website and generate the script tags through a React component.

I think the API would look like this:

```js
import Fluor from "fluor"

Fluor("div.someClass", ({on, toggleClass}) => {
  on("click", "span", toggleClass("hide"))
})
```

**Comment by CyrilKrylatov** [comment]
Sounds good for me!
